### PR TITLE
Add normalizer.PackageNormalizer to gh-pages

### PR DESCRIPTION
**Pull request by Janmm14**

### CODE REVIEW

**Comment by Janmm14** [comment]
hello again

**Comment by Janmm14** [comment]
@samczsun

**Comment by ThisTestUser** [comment]
It got added a while ago, close PR?

**Comment by Janmm14** [comment]
@ThisTestUser No, you need to look at the branch this PR is going to.

**Comment by samczsun** [comment]
it only took a year to get this merged!!

**Pull request merged**
