### PR TITLE
Remove max method size

### PR DESCRIPTION
**Pull request by FFY00**
Some obfuscators resize method to be over 64K.

### CODE REVIEW

**Comment by Janmm14** [comment]
@FFY00 Methods >64K are not allowed according to the jvm sepcification and such methods shouldn't even load at all.

**Comment by FFY00** [comment]
Yes, it is supposed to be denied by the jvm but some obfuscators still add junk code to make methods over 64K. Maybe Oracle removed this limitation in newer version of the jvm.

**Comment by Janmm14** [comment]
It should be definitely checked whether the limit got removed before removing it in here.

**Comment by FFY00** [comment]
I think the obfuscators are adding methods over 64K just to crash deobfuscators. There's no real harm in removing this verification.

**Comment by Janmm14** [comment]
Then remove it.

**Comment by ThisTestUser** [comment]
What obfuscator does that?

**Comment by samczsun** [comment]
Do you have any samples which exhibit this behavior? If absolutely necessary, I would prefer we catch the exception and handle it in the deobfuscator instead of inside the ASM code (which I am aiming to remove some point in the future because maintaining forks of active projects is a PITA)

**Pull request closed without merging**
