### PR TITLE
Fix Errors with parsing an array of chars

### PR DESCRIPTION
**Pull request by ThisTestUser**
By casting the value to char first. Prevents IllegalArgumentException from Array.set.

### CODE REVIEW

**Comment by koxu1996** [comment]
I am getting `argument type mismatch` for `array.value()` which is instance of `byte[]`. Maybe it should be unboxed too?

**Comment by ThisTestUser** [comment]
If you have permission, would you be able to send the jar (or class) that has this problem?

**Comment by koxu1996** [comment]
It's [BurpSuite Free](https://portswigger.net/burp/releases/download?product=free&version=1.7.26&type=jar) which is obfuscated with ZKM5.3.3.

Console output:
```
Reading complete. Loading hierachy


Transforming

Rearranged 58983 goto blocks
Removed 125 continous gotos
Removed 3573 unconditional switches
Removed 107308 dead instructions
Removed 0 nops
Removed 4882 goto unconditional jumps
Removed 0 ldc-pop patterns
Removed 11 ldc-swap-invoke-swap-pop patterns
Removed 0 redundant traps
Rearranged 3573 goto blocks
Removed 5 continous gotos
Removed 0 unconditional switches
Removed 3633 dead instructions
Removed 0 nops
Removed 0 goto unconditional jumps
Removed 0 ldc-pop patterns
Removed 0 ldc-swap-invoke-swap-pop patterns
Removed 0 redundant traps
Rearranged 0 goto blocks
Removed 1 continous gotos
Removed 0 unconditional switches
Removed 0 dead instructions
Removed 0 nops
Removed 0 goto unconditional jumps
Removed 0 ldc-pop patterns
Removed 0 ldc-swap-invoke-swap-pop patterns
Removed 0 redundant traps
Error while fully initializing burp/l8
java.lang.IllegalArgumentException: argument type mismatch
	at java.lang.reflect.Array.set(Native Method)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayStore(MethodExecutor.java:184)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:507)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$11(StringEncryptionTransformer.java:250)
	at java.util.HashMap$Values.forEach(HashMap.java:980)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:198)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:172)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:105)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
...
```

**Comment by ThisTestUser** [comment]
You could try doing what I do, except that you check if its a byte[].

**Comment by koxu1996** [comment]
It fixed `argument type mismatch` for my file :+1: but still there are lot of null pointer exceptions, so I will try to write ZKM deobfuscator on my own.

**Comment by ThisTestUser** [comment]
There's another error with tableswitch:
`case TABLESWITCH: {
                        int x = stack.remove(0).intValue();
                        TableSwitchInsnNode cast = (TableSwitchInsnNode) now;
                        int offset = cast.min;
                        if (x < cast.labels.size() + offset && x - offset >= 0) {
                            now = cast.labels.get(x - offset);
                        } else {
                            now = cast.dflt;
                        }
                        break;
                    }`

**Pull request closed without merging**
