### PR TITLE
Attempt fixing #645: Loop allatori before method removal

### PR DESCRIPTION
**Pull request by Janmm14**
Also improves the allatori method detection slightly

### CODE REVIEW

**Comment by Janmm14** [comment]
(this worked on some allatori samples i've got while scanning free spigotmc plugins for obfuscation)

**Comment by ItzSomebody** [comment]
I think that this looks pretty fine for a temporary fixing of #645.; however, I think that you would also agree in that wrapping the entire transformer in a do-while loop is somewhat unsightly even if it makes deobfuscation easier for the inexperienced end-user.

Thoughts on modifying the detectors to recommend running the transformer `n` times along with making the "cleanup" portions a separate transformer?

**Comment by Janmm14** [comment]
For smartredo to be actually useful we'd have to split all the cleanups from the transformers.

As many cleanup methods, like the one allatori uses, rely on data from the actual deobfuscation step, this would require some new system of persistent data.

And static variables are not the solution.

In the back of mind I also want to remove the static abuse in MethodExecutor (shift into Context), which causes a mem leak for the gui.

**Comment by ItzSomebody** [comment]
> For smartredo to be actually useful we'd have to split all the cleanups from the transformers.

Correct.  In my opinion, this (removing cleanups from transformer) is also a better idea in general because of the various complications that have arisen of it.  However, as you pointed out:

> As many cleanup methods, like the one allatori uses, rely on data from the actual deobfuscation step, this would require some new system of persistent data.

Yeah, this is a huge problem if we want to remove *only* the ones that got touched by the encryption transformer.  A possible workaround is to just ignore the need for persistent data altogether and remove all decryption methods.  If needed, it should be pretty feasible to implement something via the config to ignore specific packages/classes/methods.  Thoughts?

> And static variables are not the solution.

I would most certainly hope not.  We already have more than enough of that already.  

> In the back of mind I also want to remove the static abuse in MethodExecutor (shift into Context), which is probably the cause of the mem leak in the gui.

I agree and this is a huge one.  Everything under the executor package has been a pain in the rear to even look at (not even mentioning the monstrosity that JVMMethodProvider has become) and desperately needs a rewrite.

In fact, I would not even stop there but claim that the entire deobfuscator desperately needs a redesign.  There are a lot of design issues that should have been remedied ages ago but have not because the work involved to edit the current codebase is just not worth it.  The issue you also brought up in Discord is also one that is not extremely easy to fix because of the way the deobfuscator is designed.

**Comment by Janmm14** [comment]
IMaybe let cleanup scan if the method is still called somewhere.

**Comment by Janmm14** [comment]
#762

**Pull request closed without merging**
